"""
AMUSE Python bindings for NBODY7.

The MPI-IPC worker is generated by ``amusifier`` from this file and built
against the Fortran module ``Nbody7Interface`` (implemented in
``interface.f90``). One Fortran-glue worker is compiled, then linked four
times against four per-variant static libraries to produce four binaries:

* ``nbody7_worker``      -- portable scalar (default; cpu wheel)
* ``nbody7_sse_worker``  -- x86 SSE intrinsics  (sse wheel)
* ``nbody7_avx_worker``  -- x86 AVX intrinsics  (avx wheel)
* ``nbody7_gpu_worker``  -- CUDA                (gpu wheel)

The user picks one at runtime via the ``mode`` keyword:

    code = Nbody7(mode=Nbody7Interface.MODE_AVX)
    code = Nbody7(mode='gpu')

The matching wheel must be installed (``amuse-nbody7-avx``,
``amuse-nbody7-gpu``, ...). Each variant wheel ships only the worker
binary; the Python interface here is shared across all variants.

This module exposes two classes:

* :class:`Nbody7Interface` -- the low-level legacy-function specification
  that mirrors every Fortran subroutine. It inherits the standard
  :class:`GravitationalDynamicsInterface` and :class:`GravityFieldInterface`
  so the bulk of the AMUSE community-code contract (``new_particle``,
  ``get_state``, ``evolve_model``, ``get_gravity_at_point``, ...) is
  picked up automatically; only NBODY7-specific extras are declared here.

* :class:`Nbody7` -- the high-level user-facing wrapper, inheriting
  :class:`GravitationalDynamics` and :class:`GravityFieldCode`. It wires
  the NBODY7 parameters into the AMUSE parameter machinery so a user can
  write ``code.parameters.RBAR = 1.0 | units.parsec`` etc.

Modelled on :mod:`amuse_nbody6xx.interface` (Maxwell X. TSAI/CAI, 2014)
and :mod:`amuse_phigrape.interface` (PhiGRAPE; per-variant worker
dispatch).
"""

from amuse.community import *
from amuse.community.interface.gd import (
    GravitationalDynamicsInterface,
    GravitationalDynamics,
    GravityFieldInterface,
    GravityFieldCode,
)


# ---------------------------------------------------------------------------
# Low-level legacy-function specification
# ---------------------------------------------------------------------------

class Nbody7Interface(
    CodeInterface,
    GravitationalDynamicsInterface,
    GravityFieldInterface,
):
    """Legacy-function bindings for the NBODY7 MPI-IPC worker.

    The standard gravity / gravity-field hooks are inherited from the
    parent interfaces, so only NBODY7-specific accessors appear below.
    """

    use_modules = ["Nbody7Interface"]

    # Variant selectors. Pass one as the ``mode`` keyword to dispatch to
    # the matching worker binary at spawn time. The corresponding wheel
    # (amuse-nbody7, amuse-nbody7-sse, amuse-nbody7-avx, amuse-nbody7-gpu)
    # must be installed; an unknown mode falls back to the CPU worker.
    MODE_CPU = 'cpu'
    MODE_SSE = 'sse'
    MODE_AVX = 'avx'
    MODE_GPU = 'gpu'

    def __init__(self, mode=MODE_CPU, **keyword_arguments):
        CodeInterface.__init__(
            self,
            name_of_the_worker=self.name_of_the_worker(mode),
            **keyword_arguments,
        )

    def name_of_the_worker(self, mode):
        if mode == self.MODE_CPU:
            return 'nbody7_worker'
        if mode == self.MODE_SSE:
            return 'nbody7_sse_worker'
        if mode == self.MODE_AVX:
            return 'nbody7_avx_worker'
        if mode == self.MODE_GPU:
            return 'nbody7_gpu_worker'
        # Unknown mode -> fall back to the CPU worker (always shipped
        # by the base amuse-nbody7 wheel).
        return 'nbody7_worker'

    # -----------------------------------------------------------------
    # Per-particle attributes beyond the standard GD interface (mass,
    # position, velocity, radius). NBODY7 also tracks an integer name
    # (preserved through regularizations) and a stellar-evolution type
    # code (KSTAR). Wired into ``code.particles`` via
    # ``define_particle_sets`` below.
    # -----------------------------------------------------------------

    @legacy_function
    def set_name():
        """Set the integer ``NAME`` (identity tag) of a particle."""
        function = LegacyFunctionSpecification()
        function.addParameter("index_of_the_particle", dtype="int32",
                              direction=function.IN)
        function.addParameter("name", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        function.can_handle_array = True
        return function

    @legacy_function
    def get_name():
        """Get the integer ``NAME`` of a particle."""
        function = LegacyFunctionSpecification()
        function.addParameter("index_of_the_particle", dtype="int32",
                              direction=function.IN)
        function.addParameter("name", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        function.can_handle_array = True
        return function

    @legacy_function
    def set_kstar():
        """Set the stellar-evolution type code KSTAR (0..15; SSE/BSE)."""
        function = LegacyFunctionSpecification()
        function.addParameter("index_of_the_particle", dtype="int32",
                              direction=function.IN)
        function.addParameter("kstar", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        function.can_handle_array = True
        return function

    @legacy_function
    def get_kstar():
        """Get the stellar-evolution type code KSTAR (0..15; SSE/BSE)."""
        function = LegacyFunctionSpecification()
        function.addParameter("index_of_the_particle", dtype="int32",
                              direction=function.IN)
        function.addParameter("kstar", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        function.can_handle_array = True
        return function

    # -----------------------------------------------------------------
    # Physical-units conversion factors (read-only, populated by
    # Block/units.f during the START sequence — i.e. after the first
    # evolve_model triggers CALL NBODY6). Exposed as code-level
    # properties (``code.tstar``, ``code.vstar``) via define_properties
    # in the high-level Nbody7 class. Both come back unitful from
    # AMUSE because of the unit annotations on the legacy spec.
    # -----------------------------------------------------------------

    @legacy_function
    def get_tstar():
        """Conversion factor: 1 N-body time unit -> TSTAR Myr."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64",
                              direction=function.OUT, unit=units.Myr)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_vstar():
        """Conversion factor: 1 N-body velocity unit -> VSTAR km/s."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64",
                              direction=function.OUT,
                              unit=units.kms)
        function.result_type = "int32"
        return function

    # -----------------------------------------------------------------
    # KZ option array (50 integer flags controlling NBODY7 behaviour)
    # -----------------------------------------------------------------

    @legacy_function
    def set_kz():
        """Set ``KZ(option)`` to ``val``."""
        function = LegacyFunctionSpecification()
        function.addParameter("option", dtype="int32", direction=function.IN)
        function.addParameter("val", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_kz():
        """Get ``KZ(option)``."""
        function = LegacyFunctionSpecification()
        function.addParameter("option", dtype="int32", direction=function.IN)
        function.addParameter("val", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        return function

    # -----------------------------------------------------------------
    # Time-step parameters
    # -----------------------------------------------------------------

    @legacy_function
    def set_nnbmax():
        """Set the maximum neighbour-list length NNBMAX.

        Should be sensibly smaller than N (a few times the average
        neighbour count). The NBODY7 default for standalone runs is
        N / 4 or so; here the AMUSE-mode initial value is 300 which
        is appropriate for moderate N but should be lowered for small
        clusters (e.g. NNBMAX < N).
        """
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_nnbmax():
        """Get the maximum neighbour-list length NNBMAX."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_eta():
        """Set both irregular (ETAI) and regular (ETAR) time-step parameters."""
        function = LegacyFunctionSpecification()
        function.addParameter("eta", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_eta():
        """Get the (currently common) NBODY7 time-step parameter."""
        function = LegacyFunctionSpecification()
        function.addParameter("eta", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_etai():
        """Set the irregular-force time-step parameter ETAI."""
        function = LegacyFunctionSpecification()
        function.addParameter("etai", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_etai():
        """Get the irregular-force time-step parameter ETAI."""
        function = LegacyFunctionSpecification()
        function.addParameter("etai", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_etar():
        """Set the regular-force time-step parameter ETAR."""
        function = LegacyFunctionSpecification()
        function.addParameter("etar", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_etar():
        """Get the regular-force time-step parameter ETAR."""
        function = LegacyFunctionSpecification()
        function.addParameter("etar", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_etau():
        """Set the unperturbed-KS time-step parameter ETAU."""
        function = LegacyFunctionSpecification()
        function.addParameter("etau", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_etau():
        """Get the unperturbed-KS time-step parameter ETAU."""
        function = LegacyFunctionSpecification()
        function.addParameter("etau", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    # -----------------------------------------------------------------
    # Output / diagnostics intervals
    # -----------------------------------------------------------------

    @legacy_function
    def set_dtadj():
        """Set the parameter-adjustment interval DTADJ (N-body time)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_dtadj():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_deltat():
        """Set the diagnostic-output interval DELTAT (N-body time)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_deltat():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_tcrit():
        """Set the integration end time TCRIT (N-body time)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_tcrit():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    # -----------------------------------------------------------------
    # Step / close-encounter limits
    # -----------------------------------------------------------------

    @legacy_function
    def set_dtmin():
        """Set the minimum block time-step DTMIN."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_dtmin():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_rmin():
        """Set the close-encounter distance RMIN (N-body units)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_rmin():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_eclose():
        """Set the close binary energy threshold ECLOSE."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_eclose():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_gmin():
        """Set the lower perturbation threshold GMIN."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_gmin():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_gmax():
        """Set the upper perturbation threshold GMAX."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_gmax():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    # -----------------------------------------------------------------
    # Physical-units scaling
    # -----------------------------------------------------------------

    @legacy_function
    def set_rbar():
        """Set the length scale RBAR (parsec per N-body unit length)."""
        function = LegacyFunctionSpecification()
        function.addParameter(
            "val", dtype="float64", direction=function.IN, unit=units.parsec
        )
        function.result_type = "int32"
        return function

    @legacy_function
    def get_rbar():
        function = LegacyFunctionSpecification()
        function.addParameter(
            "val", dtype="float64", direction=function.OUT, unit=units.parsec
        )
        function.result_type = "int32"
        return function

    @legacy_function
    def set_zmbar():
        """Set the mean particle mass ZMBAR (solar masses)."""
        function = LegacyFunctionSpecification()
        function.addParameter(
            "val", dtype="float64", direction=function.IN, unit=units.MSun
        )
        function.result_type = "int32"
        return function

    @legacy_function
    def get_zmbar():
        function = LegacyFunctionSpecification()
        function.addParameter(
            "val", dtype="float64", direction=function.OUT, unit=units.MSun
        )
        function.result_type = "int32"
        return function

    @legacy_function
    def set_qe():
        """Set the relative energy-error tolerance QE."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_qe():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    # -----------------------------------------------------------------
    # Particle-setup parameters that share the DATA line in
    # input_bse-style runs (NBIN0, NHI0, ZMET, DTPLOT, EPOCH0).
    # Stored in /AMUSEBLK/ and re-injected into the matching COMMON
    # variables inside Block/data.f. Set BEFORE commit_parameters().
    # -----------------------------------------------------------------

    @legacy_function
    def get_nbin0():
        """Get the primordial binary count (default 0)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_nbin0():
        """Set the primordial binary count."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_nhi0():
        """Get the primordial hierarchy count (default 0)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_nhi0():
        """Set the primordial hierarchy count."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_zmet():
        """Get the metallicity Z (default 0.02 = solar)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_zmet():
        """Set the metallicity Z (mass fraction; clipped to [1e-4, 0.03] in DATA)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_dtplot():
        """Get the HR-diagram output interval DTPLOT (N-body time; default 10)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_dtplot():
        """Set the HR-diagram output interval DTPLOT."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_epoch0():
        """Get the initial BSE epoch (Myr; default 0)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_epoch0():
        """Set the initial BSE epoch (Myr)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    # -----------------------------------------------------------------
    # SSE / BSE stellar-evolution parameters (active when KZ(19) >= 3).
    #
    # These 26 values are read by Block/data.f from the file
    # 'input_bse' in standalone runs. Under AMUSE the read is gated;
    # default values match the canonical input_bse and can be tuned
    # individually via the setters below. Set BEFORE commit_parameters.
    #
    # All accessors are prefixed bse_ to keep the namespace organized
    # and to avoid clashes with other AMUSE community-code parameters.
    # -----------------------------------------------------------------

    # ---- BSE: 16 REAL*8 parameters ---------------------------------

    @legacy_function
    def get_bse_neta():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_neta():
        """Reimers wind mass-loss coefficient (default 0.5)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_bwind():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_bwind():
        """Binary-enhanced mass-loss parameter (default 0.0)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_hewind():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_hewind():
        """Helium-star mass-loss factor (default 1.0)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_wconst():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_wconst():
        """Wind-constant scaling (default 1.0)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_alpha1():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_alpha1():
        """Common-envelope efficiency parameter (default 1.0)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_lambda():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_lambda():
        """Common-envelope binding-energy parameter (default 0.5)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_mxns():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_mxns():
        """Maximum NS mass before BH formation (Msun; default 2.5)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_ftzacc():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_ftzacc():
        """Mass-transfer thermal-timescale acceptance fraction (default 0.5)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_disp():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_disp():
        """Velocity dispersion of NS natal kicks (km/s; default 265)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_beta():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_beta():
        """Wind-velocity factor (default 0.125)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_psii():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_psii():
        """Wind-accretion efficiency (default 1.0)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_acc2():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_acc2():
        """Bondi-Hoyle accretion factor (default 1.5)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_epsnov():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_epsnov():
        """Nova retention efficiency (default 1e-3)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_eddfac():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_eddfac():
        """Eddington-limit factor for accretion (default 1.0)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_gamm1():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_gamm1():
        """Angular-momentum loss parameter (default -1.0)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_fmrg():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_fmrg():
        """Merger fraction parameter (default 0.5)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    # ---- BSE: 10 INTEGER parameters --------------------------------

    @legacy_function
    def get_bse_ceflag():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_ceflag():
        """Common-envelope outcome flag (default 0)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_tflag():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_tflag():
        """Tidal-circularization flag (default 0)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_ifflag():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_ifflag():
        """Initial-final mass relation flag (default 0)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_wdflag():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_wdflag():
        """White-dwarf cooling flag (default 1)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_bhflag():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_bhflag():
        """BH formation / kick model selector (default 3)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_nsflag():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_nsflag():
        """NS formation / mass model selector (default 3)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_psflag():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_psflag():
        """Pair-instability supernova flag (default 1)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_kmech():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_kmech():
        """Kick mechanism selector (default 1)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_ecflag():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_ecflag():
        """Electron-capture SN flag (default 1)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_bse_edflag():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_bse_edflag():
        """Eddington-limit on accretion flag (default 0)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_archain_params():
        """Set the ARCHAIN startup parameters (CLIGHT, NBH, IDIS).

        These three values are read from STDIN by Block/ksint.f and
        ARchain/chain.f the first time a KS pair or chain regularization
        is invoked. Under AMUSE the STDIN reads are gated and the values
        come from this setter via the /AMUSEBLK/ COMMON block.

        * CLIGHT : speed of light in N-body units (default 20000).
                   Lowering it strengthens post-Newtonian effects;
                   physical c is recovered from VSTAR via 3.0E5 / VSTAR
                   km/s.
        * NBH    : ARCHAIN black-hole flag (default 0).
        * IDIS   : disruption-mode flag (default 0 = pure-BH treatment;
                   >0 enables star-BH disruption checks).
        """
        function = LegacyFunctionSpecification()
        function.addParameter("clight", dtype="float64",
                              direction=function.IN)
        function.addParameter("nbh", dtype="int32", direction=function.IN)
        function.addParameter("idis", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_archain_params():
        """Get the current ARCHAIN startup parameters."""
        function = LegacyFunctionSpecification()
        function.addParameter("clight", dtype="float64",
                              direction=function.OUT)
        function.addParameter("nbh", dtype="int32", direction=function.OUT)
        function.addParameter("idis", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_rs0():
        """Set the initial neighbour-sphere radius RS0 (N-body units)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_rs0():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function

    # -----------------------------------------------------------------
    # AMUSE-mode control parameters (the ones in /AMUSEBLK/)
    # -----------------------------------------------------------------

    @legacy_function
    def set_kstart():
        """Set KSTART (1 = new run, >=2 = restart from dump)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_kstart():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_nrand():
        """Set the random-number-generator seed NRAND."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_nrand():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="int32", direction=function.OUT)
        function.result_type = "int32"
        return function

    @legacy_function
    def set_tcomp():
        """Set the wall-clock CPU budget TCOMP (minutes)."""
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.IN)
        function.result_type = "int32"
        return function

    @legacy_function
    def get_tcomp():
        function = LegacyFunctionSpecification()
        function.addParameter("val", dtype="float64", direction=function.OUT)
        function.result_type = "int32"
        return function


# ---------------------------------------------------------------------------
# High-level user-facing class
# ---------------------------------------------------------------------------

class Nbody7(GravitationalDynamics, GravityFieldCode):
    """High-level NBODY7 community code.

    Usage::

        from amuse.units import units, nbody_system
        from amuse.community.nbody7.interface import Nbody7

        converter = nbody_system.nbody_to_si(1.0e4 | units.MSun, 1.0 | units.parsec)
        code = Nbody7(converter)
        code.parameters.RBAR  = 1.0 | units.parsec
        code.parameters.ZMBAR = 0.7 | units.MSun
        code.parameters.ETAI  = 0.04
        code.parameters.ETAR  = 0.04
        code.particles.add_particles(my_cluster)
        code.evolve_model(10.0 | units.Myr)
    """

    def __init__(self, convert_nbody=None,
                 mode=Nbody7Interface.MODE_CPU, **kargs):
        GravitationalDynamics.__init__(
            self,
            Nbody7Interface(mode=mode, **kargs),
            convert_nbody,
            **kargs,
        )

    # -----------------------------------------------------------------
    # State machine
    # -----------------------------------------------------------------

    def define_state(self, handler):
        GravitationalDynamics.define_state(self, handler)
        GravityFieldCode.define_state(self, handler)

        # Allow editing particle state in RUN; transition to a CHANGED
        # state and require synchronize_model to step back to RUN.
        # Mirrors the nbody6xx behaviour.
        handler.add_method("EDIT", "set_state")
        handler.add_method("EDIT", "set_velocity")
        handler.add_method("EDIT", "set_mass")
        handler.add_method("EDIT", "set_position")
        handler.add_method("CHANGED", "before_get_parameter")

        handler.add_transition("RUN", "CHANGED", "set_state", False)
        handler.add_transition("RUN", "CHANGED", "set_velocity", False)
        handler.add_transition("RUN", "CHANGED", "set_mass", False)
        handler.add_transition("RUN", "CHANGED", "set_position", False)
        handler.add_transition("CHANGED", "RUN", "synchronize_model")

        handler.add_method("CHANGED", "get_state")
        handler.add_method("CHANGED", "get_mass")
        handler.add_method("CHANGED", "get_position")
        handler.add_method("CHANGED", "get_velocity")

    # -----------------------------------------------------------------
    # Particle set extensions
    # -----------------------------------------------------------------

    def define_particle_sets(self, handler):
        # Pull in the standard mass / position / velocity / radius
        # wiring from GravitationalDynamics, then add NBODY7-specific
        # per-particle attributes on top.
        GravitationalDynamics.define_particle_sets(self, handler)
        handler.add_setter("particles", "set_name", names=("name",))
        handler.add_getter("particles", "get_name", names=("name",))
        handler.add_setter("particles", "set_kstar", names=("kstar",))
        handler.add_getter("particles", "get_kstar", names=("kstar",))

    # -----------------------------------------------------------------
    # Code-level properties (read-only). Accessed as ``code.tstar`` and
    # ``code.vstar`` from user scripts.
    # -----------------------------------------------------------------

    def define_properties(self, handler):
        # Pull in the standard GD properties first (kinetic_energy,
        # potential_energy, total_energy, total_mass, total_radius,
        # center_of_mass_position / _velocity, ...). Without this call
        # those attributes vanish from ``code.*`` because AMUSE only
        # registers what each define_properties override declares.
        GravitationalDynamics.define_properties(self, handler)

        # NBODY7-specific physical-units conversion factors. TSTAR
        # (Myr per N-body time) and VSTAR (km/s per N-body velocity)
        # are populated by Block/units.f during the first CALL NBODY6
        # (lazy-invoked by evolve_model). They return zero quantities
        # until then.
        handler.add_property("get_tstar", public_name="tstar")
        handler.add_property("get_vstar", public_name="vstar")

    # -----------------------------------------------------------------
    # Parameter wiring
    # -----------------------------------------------------------------

    def define_parameters(self, handler):
        # Inherited from the standard gravity interface:
        handler.add_method_parameter(
            "get_eps2",
            "set_eps2",
            "epsilon_squared",
            "smoothing parameter for gravity calculations "
            "(NBODY7 ignores; regularized integrator)",
            default_value=0.0 | nbody_system.length * nbody_system.length,
        )

        handler.add_method_parameter(
            "get_begin_time",
            "set_begin_time",
            "begin_time",
            "model time to start the simulation at",
            default_value=0.0 | nbody_system.time,
        )

        # Neighbour-list size
        handler.add_method_parameter(
            "get_nnbmax",
            "set_nnbmax",
            "NNBMAX",
            "Maximum neighbour-list length per particle "
            "(should be a few times the typical neighbour count, < N)",
            default_value=300,
        )

        # Time-step parameters
        #
        # Note: do NOT expose ``timestep_parameter`` (the convenience
        # setter that writes ETAI = ETAR = eta) as a parameter here.
        # If we did, every commit_parameters() would replay its
        # default value through set_eta() and clobber any user-supplied
        # ETAI / ETAR. Users who want to set both at once can still
        # call code.set_eta(value) explicitly as a method.
        handler.add_method_parameter(
            "get_etai",
            "set_etai",
            "ETAI",
            "Irregular-force time-step parameter",
            default_value=0.05,
        )

        handler.add_method_parameter(
            "get_etar",
            "set_etar",
            "ETAR",
            "Regular-force time-step parameter",
            default_value=0.05,
        )

        handler.add_method_parameter(
            "get_etau",
            "set_etau",
            "ETAU",
            "Unperturbed-KS time-step parameter",
            default_value=0.1,
        )

        # Output / diagnostics intervals
        handler.add_method_parameter(
            "get_dtadj",
            "set_dtadj",
            "DTADJ",
            "Parameter-adjustment interval (N-body time)",
            default_value=1.0,
        )

        handler.add_method_parameter(
            "get_deltat",
            "set_deltat",
            "DELTAT",
            "Diagnostic-output interval (N-body time)",
            default_value=1.0,
        )

        handler.add_method_parameter(
            "get_tcrit",
            "set_tcrit",
            "TCRIT",
            "Termination time of the run (N-body time)",
            default_value=1.0e10,
        )

        # Step / close-encounter limits
        handler.add_method_parameter(
            "get_dtmin",
            "set_dtmin",
            "DTMIN",
            "Minimum block time-step",
            default_value=1.0e-4,
        )

        handler.add_method_parameter(
            "get_rmin",
            "set_rmin",
            "RMIN",
            "Close-encounter distance (N-body units)",
            default_value=0.01,
        )

        handler.add_method_parameter(
            "get_eclose",
            "set_eclose",
            "ECLOSE",
            "Close binary energy threshold",
            default_value=1.0,
        )

        handler.add_method_parameter(
            "get_gmin",
            "set_gmin",
            "GMIN",
            "Lower perturbation threshold for KS regularization",
            default_value=1.0e-6,
        )

        handler.add_method_parameter(
            "get_gmax",
            "set_gmax",
            "GMAX",
            "Upper perturbation threshold for KS regularization",
            default_value=0.01,
        )

        # Physical-units scaling
        handler.add_method_parameter(
            "get_rbar",
            "set_rbar",
            "RBAR",
            "Length scale for one N-body unit of length",
            default_value=1.0 | units.parsec,
        )

        handler.add_method_parameter(
            "get_zmbar",
            "set_zmbar",
            "ZMBAR",
            "Mean particle mass",
            default_value=0.7 | units.MSun,
        )

        handler.add_method_parameter(
            "get_qe",
            "set_qe",
            "QE",
            "Relative energy-error tolerance",
            default_value=2.0e-5,
        )

        handler.add_method_parameter(
            "get_rs0",
            "set_rs0",
            "RS0",
            "Initial neighbour-sphere radius (N-body units)",
            default_value=0.14,
        )

        # AMUSE-mode control
        handler.add_method_parameter(
            "get_kstart",
            "set_kstart",
            "KSTART",
            "1 = new run, 2..5 = restart from previous dump",
            default_value=1,
        )

        handler.add_method_parameter(
            "get_nrand",
            "set_nrand",
            "NRAND",
            "Random-number-generator seed",
            default_value=4353,
        )

        handler.add_method_parameter(
            "get_tcomp",
            "set_tcomp",
            "TCOMP",
            "Wall-clock CPU budget (minutes)",
            default_value=1.0e4,
        )

        # ----- Particle-setup parameters (DATA line items) -----
        handler.add_method_parameter(
            "get_nbin0", "set_nbin0", "NBIN0",
            "Primordial binary count", default_value=0,
        )
        handler.add_method_parameter(
            "get_nhi0", "set_nhi0", "NHI0",
            "Primordial hierarchy count", default_value=0,
        )
        handler.add_method_parameter(
            "get_zmet", "set_zmet", "ZMET",
            "Metallicity Z (mass fraction)", default_value=0.02,
        )
        handler.add_method_parameter(
            "get_dtplot", "set_dtplot", "DTPLOT",
            "HR-diagram output interval (N-body time)", default_value=10.0,
        )
        handler.add_method_parameter(
            "get_epoch0", "set_epoch0", "EPOCH0",
            "Initial BSE epoch (Myr)", default_value=0.0,
        )

        # ----- SSE / BSE parameters (active when KZ(19) >= 3) -----
        handler.add_method_parameter(
            "get_bse_neta", "set_bse_neta", "bse_neta",
            "Reimers wind mass-loss coefficient", default_value=0.5,
        )
        handler.add_method_parameter(
            "get_bse_bwind", "set_bse_bwind", "bse_bwind",
            "Binary-enhanced mass-loss parameter", default_value=0.0,
        )
        handler.add_method_parameter(
            "get_bse_hewind", "set_bse_hewind", "bse_hewind",
            "Helium-star mass-loss factor", default_value=1.0,
        )
        handler.add_method_parameter(
            "get_bse_wconst", "set_bse_wconst", "bse_wconst",
            "Wind-constant scaling", default_value=1.0,
        )
        handler.add_method_parameter(
            "get_bse_alpha1", "set_bse_alpha1", "bse_alpha1",
            "Common-envelope efficiency parameter", default_value=1.0,
        )
        handler.add_method_parameter(
            "get_bse_lambda", "set_bse_lambda", "bse_lambda",
            "Common-envelope binding-energy parameter", default_value=0.5,
        )
        handler.add_method_parameter(
            "get_bse_mxns", "set_bse_mxns", "bse_mxns",
            "Maximum NS mass before BH formation (Msun)", default_value=2.5,
        )
        handler.add_method_parameter(
            "get_bse_ftzacc", "set_bse_ftzacc", "bse_ftzacc",
            "Mass-transfer thermal-timescale acceptance fraction",
            default_value=0.5,
        )
        handler.add_method_parameter(
            "get_bse_disp", "set_bse_disp", "bse_disp",
            "Velocity dispersion of NS natal kicks (km/s)",
            default_value=265.0,
        )
        handler.add_method_parameter(
            "get_bse_beta", "set_bse_beta", "bse_beta",
            "Wind-velocity factor", default_value=0.125,
        )
        handler.add_method_parameter(
            "get_bse_psii", "set_bse_psii", "bse_psii",
            "Wind-accretion efficiency", default_value=1.0,
        )
        handler.add_method_parameter(
            "get_bse_acc2", "set_bse_acc2", "bse_acc2",
            "Bondi-Hoyle accretion factor", default_value=1.5,
        )
        handler.add_method_parameter(
            "get_bse_epsnov", "set_bse_epsnov", "bse_epsnov",
            "Nova retention efficiency", default_value=1.0e-3,
        )
        handler.add_method_parameter(
            "get_bse_eddfac", "set_bse_eddfac", "bse_eddfac",
            "Eddington-limit factor for accretion", default_value=1.0,
        )
        handler.add_method_parameter(
            "get_bse_gamm1", "set_bse_gamm1", "bse_gamm1",
            "Angular-momentum loss parameter", default_value=-1.0,
        )
        handler.add_method_parameter(
            "get_bse_fmrg", "set_bse_fmrg", "bse_fmrg",
            "Merger fraction parameter", default_value=0.5,
        )
        handler.add_method_parameter(
            "get_bse_ceflag", "set_bse_ceflag", "bse_ceflag",
            "Common-envelope outcome flag", default_value=0,
        )
        handler.add_method_parameter(
            "get_bse_tflag", "set_bse_tflag", "bse_tflag",
            "Tidal-circularization flag", default_value=0,
        )
        handler.add_method_parameter(
            "get_bse_ifflag", "set_bse_ifflag", "bse_ifflag",
            "Initial-final mass relation flag", default_value=0,
        )
        handler.add_method_parameter(
            "get_bse_wdflag", "set_bse_wdflag", "bse_wdflag",
            "White-dwarf cooling flag", default_value=1,
        )
        handler.add_method_parameter(
            "get_bse_bhflag", "set_bse_bhflag", "bse_bhflag",
            "BH formation / kick model selector", default_value=3,
        )
        handler.add_method_parameter(
            "get_bse_nsflag", "set_bse_nsflag", "bse_nsflag",
            "NS formation / mass model selector", default_value=3,
        )
        handler.add_method_parameter(
            "get_bse_psflag", "set_bse_psflag", "bse_psflag",
            "Pair-instability supernova flag", default_value=1,
        )
        handler.add_method_parameter(
            "get_bse_kmech", "set_bse_kmech", "bse_kmech",
            "Kick mechanism selector", default_value=1,
        )
        handler.add_method_parameter(
            "get_bse_ecflag", "set_bse_ecflag", "bse_ecflag",
            "Electron-capture SN flag", default_value=1,
        )
        handler.add_method_parameter(
            "get_bse_edflag", "set_bse_edflag", "bse_edflag",
            "Eddington-limit on accretion flag", default_value=0,
        )

    # -----------------------------------------------------------------
    # Method-level unit annotations
    # -----------------------------------------------------------------

    def define_methods(self, handler):
        GravitationalDynamics.define_methods(self, handler)

        handler.add_method(
            "set_eps2",
            (nbody_system.length * nbody_system.length,),
            (handler.ERROR_CODE,),
        )
        handler.add_method(
            "get_eps2",
            (),
            (
                nbody_system.length * nbody_system.length,
                handler.ERROR_CODE,
            ),
        )

    # -----------------------------------------------------------------
    # NBODY7-specific helper: KZ option array
    # -----------------------------------------------------------------
    #
    # The 50-element KZ flag array is awkward to wire as 50 individual
    # parameters; instead expose ``code.set_kz(option, val)`` /
    # ``code.get_kz(option)`` directly. NBODY7-specific options worth
    # noting:
    #   KZ(11) = -1   enable ARCHAIN post-Newtonian chain
    #   KZ(22) = -1   enable astro-units input (auto-scaling)
    #   KZ(24) < 0    extra remnant-diagnostic outputs
    # See the NBODY7 manual (or Aarseth 2003) for the full list.
